nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: bundles/@yarnpkg/plugin-publishconfig.js
    spec: "@yarnpkg/plugin-publishconfig"

yarnPath: .yarn/releases/yarn-berry.cjs
